### RandomForest
- 집단 학습을 기반으로 고정밀 분류, 회귀, 클러스터링 등을 구현
- 학습 전용 데이터를 기반으로 다수의 의사결정트리를 만들고 만들어진 의사결정 트리를 기반으로 다수결로 결과를 유도하는 모델

### One - hot Encoding
- 숫자 데이터가 숫자로써 의미가 있으면 상관 X, 위의 데이터는 분류를 위한 데이터이므로 숫자 크기의 의미가 없음
- 이때 사용하는 것이 One - hot Encoding

### SVM
- 선을 구성하는 매개변수를 조정해서 데이터들을 구분하는 선을 찾고 이를 기반으로 패턴을 인식
- 데이터와 패턴들과의 거리 ( 마진 )을 최대로 만드는 것이 가장 좋은 결과를 얻음

#### SVM을 활용한 비만도 BMI 측정 예측
- BMI = 몸무게(kg) / (신장(m) * 신장(m))

#### BMI Data 생성
- 데이터 획득 위해 무작위로 2만명의 데이터를 생성

In [1]:
import numpy as np
np.random.seed(42)

In [2]:
def calc_bmi(h, w) :
    result = ""
    bmi = w / (h / 100) ** 2
    if bmi < 18.5 : result = "thin"
    elif bmi < 25 : result = 'normal'
    else : result = "fat"
    return result

In [3]:
calc_bmi(155, 50)

'normal'

In [6]:
fp = open("../Data/bmi.csv", "w", encoding="utf-8")
fp.write("height,weight,label\n")

cnt = {"thin":0, "normal":0, "fat":0}

for i in range (20000) :
    h = np.random.randint(120, 200)
    w = np.random.randint(35, 80)
    label = calc_bmi(h, w)
    cnt[label] += 1
    fp.write(f"{h},{w},{label}\n")

fp.close()
print("OK", cnt)

OK {'thin': 6262, 'normal': 5952, 'fat': 7786}

In [8]:
import pandas as pd

In [9]:
tbl = pd.read_csv('../Data/bmi.csv')
tbl.head()

   height  weight   label
0     137      51     fat
1     130      49     fat
2     191      78  normal
3     136      60     fat
4     124      38  normal

In [10]:
tbl.describe()

             height        weight
count  20000.000000  20000.000000
mean     159.042800     57.141450
std       23.108509     12.991412
min      120.000000     35.000000
25%      139.000000     46.000000
50%      159.000000     57.000000
75%      179.000000     68.000000
max      199.000000     79.000000

### 정규화
- 컬럼별로 최대값을 구해 최대값을 1로 만드는 작업

In [11]:
w = tbl.weight / tbl.weight.max()
h = tbl.height / tbl.height.max()

In [14]:
wh = pd.concat([w, h], axis = 'columns')
wh

         weight    height
0      0.645570  0.688442
1      0.620253  0.653266
2      0.987342  0.959799
3      0.759494  0.683417
4      0.481013  0.623116
...         ...       ...
19995  0.822785  0.839196
19996  0.886076  0.829146
19997  0.886076  0.668342
19998  0.886076  0.613065
19999  0.772152  0.628141

[20000 rows x 2 columns]

In [23]:
wh = tbl[['weight', 'height']]
lab = tbl['label']

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
train_data, test_data, train_target, test_target = \
    train_test_split(
        wh,
        lab,
        random_state=42,
        stratify=lab
    )

In [26]:
from sklearn.svm import SVC
clf = SVC

In [31]:
clf.fit(train_data, train_target);

In [32]:
print("Train :", clf.score(train_data, train_target))
print("Train :", clf.score(test_data, test_target))

Train : 0.9986666666666667
Train : 0.9958